name: terraform-reusable-module
on:
  workflow_call:
    inputs:
      terraform_version:
        required: false
        type: string
        default: "1.6.0"
      workflow_directory:
        required: false
        type: string
        default: "./terraform"

jobs:
  terraform: 
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ github.event.inputs.terraform_version }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        run: terraform destroy -auto-approve